### ISSUE TITLE
Remove float and clearfix - Modules

### ISSUE THREAD

**Issue by joergsteinhauer** [redaxscript/redaxscript#554]
Time to replace float with flexbox and get rid of clearfix as well, if necessary.

1. Remove all `float: left|right` definitions from modules when it makes sense
1. Use dynamic `flexbox` and `flex: 1`
1. Remove `assets/styles/_clearfix.css` helper, if not needed
1. Remove `clearfix` from `helper.css` in templates, if not needed
1. Remove `clearfix` from PHP, if not needed

Hints:

1. Run `grunt serve`
1. Install Redaxscript via form
1. Install Live Reload module via Terminal: `php console.php install module --alias=LiveReload`

**Comment by redaxmedia** [comment]
Done
