### ISSUE TITLE
Redaxscript for people!

### ISSUE THREAD

**Issue by koreos** [redaxscript/redaxscript#568]
Please make Redaxscript easy to use above all for people who are not webmasters or designers and then will have a lot of sponsors and money! 

Examples:
1. https://generatepress.com/premium/ or
2. https://oceanwp.org/extensions/
3. https://elementor.com/
4. very good SEO solutions https://wordpress.org/plugins/autodescription/
5. very fast on GooglePageSpeedInsights
6. also for very big projects with thousands subpages
7. no MySql

**Comment by redaxmedia** [comment]
Hello @koreos 

thank you very much for your feedback. The idea behind Redaxscript is not to reinvent something like Wordpress that is made for the end user - you need to be a developer to use Redaxscript.

1. to 3. Love the idea of having modules for typo, layout and color customization but this is too much work for a one man show. We allready have a good set of modules - feel free to suggest new ones
4. Redaxscript allready has a very good SEO with many of the features similar to that WP plugin
5. Show me a CMS that ranks better on YSlow and Pagespeed ... there is none
6. There is a PageCache module that allows very high traffic - beyond that, this CMS is one of the fastes in the world... in most cases there is no need for caching
7. This CMS also supports SQLite, MSSQL, MySQL and PostgreSQL

**Comment by NetLancer** [comment]
Surely Redaxscript has its own niche, i like it much for its slim and optimized nature while there's a number of plugins available. Not as popular and plugin/extension rich as WP though, but I mean even being not really a webDev why not give it a try, at least GUI is okay and i believe intuitive enough

**Comment by redaxmedia** [comment]
Like I said - this is a one man show, what means that I program most of the code. Therefore, I need to focus on a couple of tasks and can't provide a rich feature set.

At the moment Redaxscript 4.0.0 is on it's way to have a complete finished PHP codebase, better template tags and an basic installation that is nearly free of JavaScript / jQuery plugins as we are going to move everything to the modules.

You can read more about it on our [facebook page](https://www.facebook.com/redaxscript).

I know that life is hard for non-developers. You need to know Grunt for the bundling / compiling - or at least how to modify the existing template asset helper to work with Vanilla CSS.

So what is missing here? It's your feedback. It's youre contribution to Redaxscript! :-)

1. What parts of Redaxscript are not easy to understand
1. Where are you stucked while developing a template
1. What parts of the documentation are inconplete

**Comment by redaxmedia** [comment]
Closing this issue as there is no response.
