### ISSUE TITLE
page post panel in stored xss vulenrability

### ISSUE THREAD

**Issue by ismailtasdelen** [redaxscript/redaxscript#575]
Hello Development Team,

When I was a security researcher and student, I wanted to discover and report "XSS" vulnerability.

Version :  Powered by Redaxscript 3.3.2

Screenshot : 

![screenshot from 2018-07-18 17-27-14](https://user-images.githubusercontent.com/15425071/42888134-3b63e4ac-8ab0-11e8-938e-de6a0e4f0a9f.png)

![screenshot from 2018-07-18 17-27-36](https://user-images.githubusercontent.com/15425071/42888140-3e8f07ba-8ab0-11e8-8440-4c4d17a96f44.png)

Payload : "><img src=x onerror=alert('ismailtasdelen')>

Thanks

**Comment by redaxmedia** [comment]
Thank you for testing Redaxscript against XSS.

Unfortunately, this report is  99% not valid. Let me guess, you were logged in as god admin?

1. Administrators do have the **filtering of XSS** disabled by default - how should they post articles with special characters or add html tags? Think about it^^
2. Other groups do have the "customize" tab where the **filtering of XSS** can be enabled/disabled
3. We have a very strong [HTML Purifier](https://github.com/redaxscript/redaxscript/blob/master/includes/Html/Purifier.php) that could be penetrated by extending the [provider](https://github.com/redaxscript/redaxscript/blob/master/tests/provider/Html/purifier.json)

```
grunt phpunit --testsuite=html
```
