### ISSUE TITLE
Timezone Issue

### ISSUE THREAD

**Issue by SimonPattzone** [redaxscript/redaxscript#602]
I am having a small issue:

Admin Panel -> System -> Settings -> Formatting:
  Timezone change doesn't save to settings database table so doesn't stick.

**Comment by redaxmedia** [comment]
Hey,

thanks for pointing out this bug. I resolved it inside the master brnach via https://github.com/redaxscript/redaxscript/commit/5819e64aae787319a6d14d0eca8b100c0a2592cf.

Consider to give Redaxscript a star and have a great day.
