### ISSUE TITLE
Variable Google Fonts

### ISSUE THREAD

**Issue by redaxmedia** [redaxscript/redaxscript#609]
Once Google supports "Open Sans Condensed" as variable font we should switch from:

```
https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300;700
```

To following URL that curently produces 404 error:

```
https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300..700
```

This shoud result a valid CSS file with `font-face` definition like:

```css
@font-face {
  font-weight: 300 700;
}
```

**Comment by davelab6** [comment]
It will likely be like this

    https://fonts.googleapis.com/css2?family=Open+Sans:wdth,wght@75;300..700

**Comment by redaxmedia** [comment]
Done
