### ISSUE TITLE
no pretty url 

### ISSUE THREAD

**Issue by talhag3** [redaxscript/redaxscript#714]
does it provide a pretty URL?

![image](https://user-images.githubusercontent.com/16940319/108490718-df461280-72c4-11eb-9b6c-4dbc264fe50b.png)

**Comment by redaxmedia** [comment]
@talhag3 Sure it provides that feature but you need to have `mod_rewrite` enabled in your apache webserver.

fallback routes: https://redaxscript.com/?p=download/releases-download
routes with rewrite: https://redaxscript.com/download/releases-download
